"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta

# Load environment variables
load_dotenv()


def env_list(name, default):
    value = os.getenv(name)
    if not value:
        return tuple(default)
    return tuple(item.strip() for item in value.split(",") if item.strip())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
INTERNAL_AUTH_SECRET = os.getenv('INTERNAL_AUTH_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['backend', 'localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # Django rest framework
    'corsheaders',
    'users', # Custom user management app, handles User model & authentication
    'goals', # Goal management app, handles creation, tracking, & AI-powered breakdowns
    'tasks', # Task management app, handles individual tasks & tracking
    'conversations', # User & AI conversations app
]

# Use custom user model from users app
AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow Next.js dev server 
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Ensure Django trusts the proxy for CSRF purposes
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv('PGHOST'),
        'NAME': os.getenv('PGDATABASE'),
        'USER': os.getenv('PGUSER'),
        'PASSWORD': os.getenv('PGPASSWORD'),
        'PORT': os.getenv('PGPORT', 5432),
        'OPTIONS': {
            'sslmode': 'require',
        },
        'DISABLE_SERVER_SIDE_CURSORS': True,
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'goal_preview': '10/hour',
    },
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# AI provider routing
AI_REQUEST_TIMEOUT_SECONDS = float(os.getenv("AI_REQUEST_TIMEOUT_SECONDS", "30"))
AI_TOTAL_TIMEOUT_SECONDS = float(os.getenv("AI_TOTAL_TIMEOUT_SECONDS", "45"))
AI_RETRY_MAX_ATTEMPTS = int(os.getenv("AI_RETRY_MAX_ATTEMPTS", "2"))
AI_RETRY_MIN_SECONDS = float(os.getenv("AI_RETRY_MIN_SECONDS", "0.5"))
AI_RETRY_MAX_SECONDS = float(os.getenv("AI_RETRY_MAX_SECONDS", "4"))
AI_MAX_OUTPUT_TOKENS = int(os.getenv("AI_MAX_OUTPUT_TOKENS", "4096"))

AI_PROVIDER_ORDER = env_list("AI_PROVIDER_ORDER", ("gemini",))
AI_ROUTES = {
    "goal_decomposition": env_list(
        "AI_DECOMPOSITION_PROVIDERS",
        AI_PROVIDER_ORDER,
    ),
    "plan_iteration": env_list(
        "AI_PLAN_ITERATION_PROVIDERS",
        AI_PROVIDER_ORDER,
    ),
}

_openrouter_headers = {
    key: value
    for key, value in {
        "HTTP-Referer": os.getenv("OPENROUTER_SITE_URL"),
        "X-Title": os.getenv("OPENROUTER_APP_NAME", "Yiyara"),
    }.items()
    if value
}

AI_PROVIDERS = {
    "gemini": {
        "BACKEND": "ai.providers.gemini_provider.GeminiProvider",
        "OPTIONS": {
            "api_key": os.getenv("GEMINI_API_KEY"),
            "model": os.getenv("GEMINI_MODEL", "gemini-2.5-flash-lite"),
            "timeout_seconds": AI_REQUEST_TIMEOUT_SECONDS,
        },
    },
    "groq": {
        "BACKEND": (
            "ai.providers.openai_compatible_provider.OpenAICompatibleProvider"
        ),
        "OPTIONS": {
            "name": "groq",
            "api_key": os.getenv("GROQ_API_KEY"),
            "base_url": os.getenv(
                "GROQ_BASE_URL",
                "https://api.groq.com/openai/v1",
            ),
            "model": os.getenv("GROQ_MODEL", "openai/gpt-oss-20b"),
            "structured_mode": "json_schema",
        },
    },
    "openrouter": {
        "BACKEND": (
            "ai.providers.openai_compatible_provider.OpenAICompatibleProvider"
        ),
        "OPTIONS": {
            "name": "openrouter",
            "api_key": os.getenv("OPENROUTER_API_KEY"),
            "base_url": os.getenv(
                "OPENROUTER_BASE_URL",
                "https://openrouter.ai/api/v1",
            ),
            "model": os.getenv("OPENROUTER_MODEL", "openrouter/free"),
            "structured_mode": "json_schema",
            "extra_headers": _openrouter_headers,
            "extra_body": {"provider": {"require_parameters": True}},
        },
    },
    "ollama": {
        "BACKEND": (
            "ai.providers.openai_compatible_provider.OpenAICompatibleProvider"
        ),
        "OPTIONS": {
            "name": "ollama",
            "api_key": os.getenv("OLLAMA_API_KEY", "ollama"),
            "base_url": os.getenv(
                "OLLAMA_BASE_URL",
                "http://localhost:11434/v1",
            ),
            "model": os.getenv("OLLAMA_MODEL", "qwen3:8b"),
            "structured_mode": "json_schema",
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
